### ISSUE TITLE
 No module named 'citypb'

### ISSUE THREAD

**Issue by EroicaX** [Sud0x67/city_brain_kit#2]
Hi, I'm trying to run in Window platform, but the citypb in the repo is  a linux compiled file, so is there a windows version of this package?

**Comment by Sud0x67** [comment]
Hi@EroicaX, cause this file is abstract from the formal docker environment, there is no a version of windows platform. But I  have some advice that may be helpful: Firstly check that if your python version is 3.7.Secondly  make sure that the path of this compied file is in your sys.path. If your problem is solved you can give a feedback here  so that others can utilize this solution.

**Comment by EroicaX** [comment]
@Sud0x67 Thanks for replying. I dont think .so files can be loaded on Windows platform, Im gonna try using docker for convinience.
